GEODE-8571: Enforce documentation errors
apache/geode-native pull request #666
Opened 2020-10-02 17:50 UTC by moleske

Authored-by: M. Oleske <michael@oleske.engineer>

Ran on [Windows](https://github.com/moleske/geode-native/actions/runs/280909801) (Visual Studio 2017 and some on Visual Studio 2019) and [Ubuntu](https://github.com/moleske/geode-native/actions/runs/280909802) (16.04 and 18.04)

This does not fix content or incorrectness in the docs, I need some feedback/help on that.  I also made some questionable decisions, see if you can find them!  Since this is going to be mostly grammar/spell check/making sure they're not lying, it is probably easier just to push your suggestions directly if you have access (box is checked for allow edits by maintainers)

2020-10-02 18:01 UTC, pivotal-jbarrett approved these changes
YES!

2020-10-02 20:58 UTC, pdxcodemonkey approved these changes
Nice.  Thanks for sweeping up around the place, Michael :)

2020-10-03 00:02 UTC, karensmolermiller requested changes

2020-10-03 00:12 UTC, moleske commented on cppcache/src/CqService.hpp
> +   * @param deltaValue to invoke listeners with
`key`, `value`, `deltaValue` are on lines 221-223 right below

2020-10-03 00:13 UTC, moleske commented on cppcache/include/geode/internal/chrono/duration.hpp
> + * @tparam Period the something else that periods
I wanted to come back and write something meaningful, but never did.  If no one has suggestions I'll just delete the documentation here

2020-10-05 21:20 UTC, moleske commented on cppcache/include/geode/internal/chrono/duration.hpp
> + * @tparam Period the something else that periods
Ended up just removing it since it is internal . Let me know what you think @karensmolermiller

2020-10-05 22:14 UTC, karensmolermiller approved these changes
Looks good.  Thanks for improving the API docs.

2020-10-05 22:16 UTC, merged