Feature/asio
apache/geode-native pull request #697
Opened 2020-11-18 17:12 UTC by albertogpz

This draft pull request includes the rebase of develop into the feature/asio branch and the solution to the hangs and aborts that were present in the branch in the integration-tests (see GEODE-8318).

All test cases are passing now, even the IPV6 one, without the need to configure IPv6 in the CMakeLists.txt file.

The code is ready for review.

2020-11-20 19:07 UTC, pdxcodemonkey commented
This is failing one of our "acceptance" tests, `SNITest.dropSNIProxy`.  This is a negative test case, so I think it's expecting a Geode exception and now it's getting the following:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  remote_endpoint: Transport endpoint is not connected
```
Command line for CI running acceptance tests is the following:
```
cd /home/geode/build/cppcache/acceptance-test && ctest -C Debug --output-on-failure --output-log test.log --timeout 600
```
You can probably repro with just this:
```
cd /home/geode/build/cppcache/acceptance-test && ctest -C Debug -R SNITest.dropSNIProxy --timeout 600
```

2020-11-20 19:09 UTC, pdxcodemonkey commented
Outstanding work, BTW!  As advertised, _everything_ else appears to be passing.  This is a huge win, thanks so much!

2020-11-23 12:46 UTC, albertogpz commented
> This is failing one of our "acceptance" tests, `SNITest.dropSNIProxy`. This is a negative test case, so I think it's expecting a Geode exception and now it's getting the following:
> 
> ```
> terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
>   what():  remote_endpoint: Transport endpoint is not connected
> ```
> 
> Command line for CI running acceptance tests is the following:
> 
> ```
> cd /home/geode/build/cppcache/acceptance-test && ctest -C Debug --output-on-failure --output-log test.log --timeout 600
> ```
> 
> You can probably repro with just this:
> 
> ```
> cd /home/geode/build/cppcache/acceptance-test && ctest -C Debug -R SNITest.dropSNIProxy --timeout 600
> ```

I forgot about the acceptance-tests :-).
I have fixed the issue in the new commit.

2020-11-23 16:43 UTC, pdxcodemonkey commented
Down to one failed test on a couple of platforms now - so close!

```
testXmlCacheCreationWithPools
```
Is timing out on Windows and RHEL7.

FYI, I'm out this week for the US holiday, so will be of limited, if any, help.  @mmartell & @mreddington can follow up as needed, I'll ping them via DM.

2020-11-25 18:59 UTC, albertogpz commented
> Down to one failed test on a couple of platforms now - so close!
> 
> ```
> testXmlCacheCreationWithPools
> ```
> 
> Is timing out on Windows and RHEL7.
> 
> FYI, I'm out this week for the US holiday, so will be of limited, if any, help. @mmartell & @mreddington can follow up as needed, I'll ping them via DM.

I managed to fix the test on windows thanks to @gaussianrecurrence . I hope it is also fixed under RHEL7.

2020-11-26 09:41 UTC, albertogpz commented
> > Down to one failed test on a couple of platforms now - so close!
> > ```
> > testXmlCacheCreationWithPools
> > ```
> > 
> > 
> > Is timing out on Windows and RHEL7.
> > FYI, I'm out this week for the US holiday, so will be of limited, if any, help. @mmartell & @mreddington can follow up as needed, I'll ping them via DM.
> 
> I managed to fix the test on windows thanks to @gaussianrecurrence . I hope it is also fixed under RHEL7.

Anyway, I have a question for @mreddington . The test case failed due to the addition of the following commit:
d2a307d80 cppcache/src/TcrEndpoint.cpp     (Matthew Reddington 2020-05-14 17:36:32 -0700 1181)   m_cacheImpl->doIfDestroyNotPending([&]()
 {

What is the reason for this change? I have not seen it in the development branch so I wonder if it is really necessary.

2020-11-26 17:24 UTC, pdxcodemonkey commented
This is passing on Windows now, and I have at least an example of it working on RHEL7 Release build.  Our Debug and Coverage builds of RHEL7 are now timing out on a test, though, which has been a problem in the past.  Here's the tail end of the output, which looks kind of strange to me.

```
[       OK ] PartitionRegionOpsTest.putPartitionedRegionWithRedundancyServerGoesDownSingleHop (60480 ms)
[----------] 1 test from PartitionRegionOpsTest (60480 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (60481 ms total)
[  PASSED  ] 1 test.
[debug 2020/11/25 21:03:47.396293 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] ThinClientPoolDM::destroy...
[debug 2020/11/25 21:03:47.396528 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] Internal fair queue size while closing is 0
[debug 2020/11/25 21:03:47.396541 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] ConnectionQueue::close( ): queue closed 
[debug 2020/11/25 21:03:47.396559 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] recursive lock: CacheImpl::doIfDestroyNotPending


0% tests passed, 1 tests failed out of 1

Total Test time (real) = 650.16 sec

The following tests FAILED:
	 27 - PartitionRegionOpsTest.putPartitionedRegionWithRedundancyServerGoesDownSingleHop (Timeout)
Errors while running CTest
```

2020-11-26 17:40 UTC, albertogpz commented
> This is passing on Windows now, and I have at least an example of it working on RHEL7 Release build. Our Debug and Coverage builds of RHEL7 appear to now be timing out on a test, though, which has been a problem in the past. Here's the tail end of the output, which looks kind of strange to me.
> 
> ```
> [       OK ] PartitionRegionOpsTest.putPartitionedRegionWithRedundancyServerGoesDownSingleHop (60480 ms)
> [----------] 1 test from PartitionRegionOpsTest (60480 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 1 test from 1 test suite ran. (60481 ms total)
> [  PASSED  ] 1 test.
> [debug 2020/11/25 21:03:47.396293 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] ThinClientPoolDM::destroy...
> [debug 2020/11/25 21:03:47.396528 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] Internal fair queue size while closing is 0
> [debug 2020/11/25 21:03:47.396541 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] ConnectionQueue::close( ): queue closed 
> [debug 2020/11/25 21:03:47.396559 UTC heavy-lifter-80e74939-d075-5450-9833-2e242c016911:1522 139806642039104] recursive lock: CacheImpl::doIfDestroyNotPending
> 
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Total Test time (real) = 650.16 sec
> 
> The following tests FAILED:
> 	 27 - PartitionRegionOpsTest.putPartitionedRegionWithRedundancyServerGoesDownSingleHop (Timeout)
> Errors while running CTest
> ```

Interesting... @gaussianrecurrence told me that he had seen a deadlock in the feature/asio branch once related to that mutex but had not been able to reproduce it again. We looked together at the code today and it appeared that a deadlock is possible after the change included by @mreddington about which I him asked above. We could try removing the call to CacheImpl::doIfDestroyNotPending in TcrEndpoint::closeConnections() to see if the timeout does not occur.

2020-12-01 20:27 UTC, mreddington commented
@albertogpz Despite it's terrible name, `doIfDestroyNotPending` ends a race condition where code tries to access the cache after it was destroyed. It's a shame we apparently need to set max connections which is only available from the distributed system when we close connections. This could cause a segfault during client shutdown.

2020-12-02 10:35 UTC, albertogpz commented
> @albertogpz Despite it's terrible name, `doIfDestroyNotPending` ends a race condition where code tries to access the cache after it was destroyed. It's a shame we apparently need to set max connections which is only available from the distributed system when we close connections. This could cause a segfault during client shutdown.

Thanks @mreddington .
@pdxcodemonkey , I have pushed a new commit to see if removing the need to use that method (and the use itself) in `TcrEndpoint::closeConnections()`, fixes the possible deadlock. I do not have a RHEL7 environment so I cannot verify if this change fixes anything. Could you please test it?

2020-12-02 17:21 UTC, gaussianrecurrence commented
> @albertogpz Despite it's terrible name, `doIfDestroyNotPending` ends a race condition where code tries to access the cache after it was destroyed. It's a shame we apparently need to set max connections which is only available from the distributed system when we close connections. This could cause a segfault during client shutdown.

Problem is that using doIfDestroyNotPending has undefined behaviour, as you are accessing the CacheImpl status equally. If it happens that the cache is removed and the mem page on which the cache was gets overwritten, doIfDestroyNotPending could try to execute the lambda.

The real issue here is that whenever ThinClientPoolDM::destroy is called, m_endpoints is not cleared
By the time ThinClientPoolDM::~ThinClientPoolDM is called, m_endpoints is to be destroyed, decrementing the reference counter to each of the container items.
If it happens that the container is holding an object which this was its latest reference, TcrEndpoint::TcrEndpoint will be called leading to undefined behaviour.

The real solution here is to make sure that before a pool destructor is called, all the references to the endpoints are cleared out.

2020-12-02 17:48 UTC, pdxcodemonkey commented
Our CI didn't run builds after the last commit, because it has a `clang-format` issue:

```
@@ -140,7 +140,7 @@ class NamingContextImpl : virtual public NamingContext {
       LOGCOORDINATOR(func);
       LOGCOORDINATOR("Dump follows:");
       dump();
-      throw -1;
+      throw - 1;
     }
     return result;
   }
```
If you fix/push this, it should kick off a new set of builds.  Thanks!

2020-12-02 18:43 UTC, albertogpz commented
> Our CI didn't run builds after the last commit, because it has a `clang-format` issue:
> 
> ```
> @@ -140,7 +140,7 @@ class NamingContextImpl : virtual public NamingContext {
>        LOGCOORDINATOR(func);
>        LOGCOORDINATOR("Dump follows:");
>        dump();
> -      throw -1;
> +      throw - 1;
>      }
>      return result;
>    }
> ```
> 
> If you fix/push this, it should kick off a new set of builds. Thanks!

Done. Strangely, it was cmake the one who changed that line in the first place to `throw -1`.

2020-12-03 18:47 UTC, pdxcodemonkey commented
This is green in CI now - can you please rebase the branch onto the latest `develop`?  We'll review it quickly and get it merged.

2020-12-03 19:30 UTC, pdxcodemonkey commented
FWIW, a rebase is liable to be unpleasant, from what I saw when attempting it.  I saved off the contents of a merge commit into `develop` as a stash, applied it to a new branch, and came up with this:  https://github.com/apache/geode-native/compare/develop...pdxcodemonkey:feature/asio-latest.  Hope this helps.

2020-12-09 07:08 UTC, albertogpz commented
> This is green in CI now - can you please rebase the branch onto the latest `develop`? We'll review it quickly and get it merged.

Done in the latest force push. Not sure why the checks are failing with merge conflicts. Everything looked correct in my local branch.

2020-12-09 23:39 UTC, pdxcodemonkey commented
Your PR is still set up to merge from your fork into the apache `feature/asio` branch, rather than `develop`.  I think if you target `develop` the conflicts will be gone.

2020-12-10 07:29 UTC, albertogpz commented
> Your PR is still set up to merge from your fork into the apache `feature/asio` branch, rather than `develop`. I think if you target `develop` the conflicts will be gone.

You are right. I changed that and now I get errors in LGTM analysis but I do not understand why.

2020-12-11 20:33 UTC, albertogpz commented
> > Your PR is still set up to merge from your fork into the apache `feature/asio` branch, rather than `develop`. I think if you target `develop` the conflicts will be gone.
> 
> You are right. I changed that and now I get errors in LGTM analysis but I do not understand why.

There was a merge commit from develop that I should not have added.
Now it is fixed and ready for review.

2020-12-11 23:01 UTC, pdxcodemonkey requested changes
Looks great, thanks again!  Just a couple of small edits, and a couple of questions to answer, then you're good to go.  I'll try to get this merged on Monday if you're ready.

2020-12-14 09:59 UTC, albertogpz commented on cppcache/src/Connector.hpp
> +class APACHE_GEODE_EXPORT Connector {
This was already there in the version of the branch I took as base. I have removed the export as I do not see the need.

2020-12-14 09:59 UTC, albertogpz commented on cppcache/src/Connector.hpp
> +  }
Class not finally exported.

2020-12-14 10:00 UTC, albertogpz commented on cppcache/src/DistributedSystem.hpp
>  };
Done by someone else in the version of the branch I took as base.

2020-12-14 10:00 UTC, albertogpz commented on cppcache/src/TcrConnection.hpp
> +      std::shared_ptr<TcrEndpoint> endpointObj,
Done by someone else in the version of the branch I took as base.

2020-12-14 10:02 UTC, albertogpz commented on defaultSystem/geode.properties
> +log-level=debug
Done by someone else in the version of the branch I took as base. I have left it as it was originally.

2020-12-14 10:04 UTC, albertogpz commented on tests/cpp/fwklib/TcpIpc.cpp
>    ACE_OS::signal(SIGPIPE, SIG_IGN);  // Ignore broken pipe
I guess you are referring to:
ssl_keys/server_keys/locator-maeve-keystore.jks
ssl_keys/server_keys/server-clementine-keystore.jks
ssl_keys/server_keys/server-dolores-keystore.jks
ssl_keys/server_keys/truststore.jks

They also came in the version of the branch I took as base. I have removed them.

2020-12-14 10:12 UTC, albertogpz commented on cppcache/src/PoolFactory.cpp
> +  //  addCheck(host, port);
Done by someone else in the version of the branch I took as base. Removed the commented out code.

2020-12-14 17:34 UTC, pdxcodemonkey commented
Well I guess we know why Connector needs to be APACHE_GEODE_EXPORT now:

```
c:\nativeclient\cppcache\src\TcpConn.hpp(33): error C2220: warning treated as error - no 'object' file generated (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
c:\nativeclient\cppcache\src\TcpConn.hpp(33): warning C4275: non dll-interface class 'apache::geode::client::Connector' used as base for dll-interface class 'apache::geode::client::TcpConn' (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
  c:\nativeclient\cppcache\src\Connector.hpp(40): note: see declaration of 'apache::geode::client::Connector' (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp)
  c:\nativeclient\cppcache\src\TcpConn.hpp(33): note: see declaration of 'apache::geode::client::TcpConn' (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp)
c:\nativeclient\cppcache\src\TcpConn.hpp(33): error C2220: warning treated as error - no 'object' file generated (compiling source file C:\nativeclient\cppcache\src\TcpSslConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
c:\nativeclient\cppcache\src\TcpConn.hpp(33): warning C4275: non dll-interface class 'apache::geode::client::Connector' used as base for dll-interface class 'apache::geode::client::TcpConn' (compiling source file C:\nativeclient\cppcache\src\TcpSslConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
  c:\nativeclient\cppcache\src\Connector.hpp(40): note: see declaration of 'apache::geode::client::Connector' (compiling source file C:\nativeclient\
```

It looks like TcpConn has also been exported and wasn't before.  Perhaps fixing that will take care of everything.

2020-12-14 18:16 UTC, albertogpz commented
> Well I guess we know why Connector needs to be APACHE_GEODE_EXPORT now:
> 
> ```
> c:\nativeclient\cppcache\src\TcpConn.hpp(33): error C2220: warning treated as error - no 'object' file generated (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
> c:\nativeclient\cppcache\src\TcpConn.hpp(33): warning C4275: non dll-interface class 'apache::geode::client::Connector' used as base for dll-interface class 'apache::geode::client::TcpConn' (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
>   c:\nativeclient\cppcache\src\Connector.hpp(40): note: see declaration of 'apache::geode::client::Connector' (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp)
>   c:\nativeclient\cppcache\src\TcpConn.hpp(33): note: see declaration of 'apache::geode::client::TcpConn' (compiling source file C:\nativeclient\cppcache\src\TcpConn.cpp)
> c:\nativeclient\cppcache\src\TcpConn.hpp(33): error C2220: warning treated as error - no 'object' file generated (compiling source file C:\nativeclient\cppcache\src\TcpSslConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
> c:\nativeclient\cppcache\src\TcpConn.hpp(33): warning C4275: non dll-interface class 'apache::geode::client::Connector' used as base for dll-interface class 'apache::geode::client::TcpConn' (compiling source file C:\nativeclient\cppcache\src\TcpSslConn.cpp) [C:\build\cppcache\shared\apache-geode.vcxproj]
>   c:\nativeclient\cppcache\src\Connector.hpp(40): note: see declaration of 'apache::geode::client::Connector' (compiling source file C:\nativeclient\
> ```
> 
> It looks like TcpConn has also been exported and wasn't before. Perhaps fixing that will take care of everything.

Let's see.

2020-12-14 18:16 UTC, pdxcodemonkey commented
Confirmed - removing APACHE_GEODE_EXPORT from TcpConn fixes my Windows build.

2020-12-14 18:18 UTC, pdxcodemonkey commented on defaultSystem/geode.properties
> +log-level=debug
Okay - we can clean this up later.

2020-12-14 18:18 UTC, pdxcodemonkey commented on cppcache/src/TcrConnection.hpp
> +      std::shared_ptr<TcrEndpoint> endpointObj,
I suppose thanks are due to @mreddington then :).  Either way, this is much better.

2020-12-14 21:00 UTC, pdxcodemonkey approved these changes

2020-12-14 21:04 UTC, merged