GEODE-8929: fix 'leaked disk space' issue in logger
apache/geode-native pull request #743
Opened 2021-02-09 20:28 UTC by pdxcodemonkey

logger wasn't calculating size of existing logs at initialization, so stopping and restarting an app without deleting logs would cause the logger to 'grow' used disk space by up to `log-disk-space-limit` each iteration.

Also added appropriate tests, and fixed a default filename issue.

Co-authored-by: Matthew Reddington <mreddington@vmware.com>

@mreddington @dihardman @davebarnes97 @karensmolermiller

2021-02-09 22:05 UTC, echobravopapa requested changes
I think there is a test case needed and Travis is red...

2021-02-09 22:05 UTC, echobravopapa commented on cppcache/src/Log.cpp
> +      logFileName ? std::string(logFileName) : std::string("geode-native.log");
is there a test checking the repeated use of the default log file name?

2021-02-10 00:02 UTC, pivotal-jbarrett commented
We really need to get out of the business of writing our own logger! ;)

2021-02-17 15:44 UTC, echobravopapa approved these changes

2021-02-17 16:01 UTC, merged