GEODE-9804: Fixes incorrect fetching of initial entries.
apache/geode-native pull request #892
Opened 2021-11-08 20:51 UTC by pivotal-jbarrett

* Makes InterestResultPolicy a proper enum.
* Adds integration benchmark for register interest.
* Cleanup methods unused arguments.

2021-11-13 16:05 UTC, pdxcodemonkey requested changes
Just a couple of small things and a few questions to answer.  Thanks, this is a big improvement!

2021-11-13 16:05 UTC, pdxcodemonkey commented on cppcache/src/ThinClientRegion.cpp
> +      auto exceptions = std::make_shared<HashMapOfException>();
Why is this map here?  Can we push it down into the `ChunkedGetAllResponse` ctor?

2021-11-13 16:05 UTC, pdxcodemonkey commented on cppcache/src/ThinClientRegion.cpp
> +      auto exceptions = std::make_shared<HashMapOfException>();
Same here - exceptions map looks like it's just a transient parameter to the `ChunkedGetAllResponse` ctor

2021-11-15 19:31 UTC, pivotal-jbarrett commented
Closing in favor of https://github.com/apache/geode-native/pull/894

2021-11-15 19:31 UTC, closed without merging