GEODE-10017: Fix servers restart within new ITs
apache/geode-native pull request #919
Opened 2022-02-04 09:55 UTC by gaussianrecurrence

- Due to a rare race-condition described on the Jira case, it could
   happen that some test cases that needed to restart a/some server(s)
   could end up getting stuck.
 - This change introduces a mechanism to verify the server process has
   been actually stopped.
 - Also, removed sleeps on some TCs which were put in place as a WA.
 - Modified all of the new IT TCs that were restarting servers in order
   to use the above mentioned mechanism, so the race-condition is
   avoided.

2022-03-02 15:56 UTC, pdxcodemonkey requested changes

2022-03-02 15:56 UTC, pdxcodemonkey commented on cppcache/integration/test/FunctionExecutionTest.cpp
> +  targetServer.wait();
Why this separation of concerns between stop() and wait()?  Is there ever a circumstance where we call stop() and don't intend for the process to actually be terminated yet when the function returns?

2022-03-02 15:56 UTC, pdxcodemonkey commented on cppcache/integration/test/PdxInstanceTest.cpp
> +    server.wait();
Okay I see this used separately here in several places, but... would it be necessary to call wait() in the other places if stop() just actually made sure the process was terminated?

2023-11-17 16:53 UTC, gaussianrecurrence commented
I haven't had the time to work on this for a long time or I think I'll have the opportunity to in the near future, hence I am closing this PR, if anyone wants to tackle this issue can take it up from its latest state.

2023-11-17 16:53 UTC, closed without merging